#ifndef DATATYPES_H
#define DATATYPES_H

enum TileState { EMPTY, FOOD, BODY_START, BODY_VERTICAL, BODY_HORIZONTAL,
                 BODY_NORTH_EAST, BODY_NORTH_WEST,
                 BODY_SOUTH_EAST, BODY_SOUTH_WEST,
                 HEAD_EAST, HEAD_WEST, HEAD_SOUTH};

#endif // DATATYPES_H
